UI: add aside chat and buttons style
IgorAleks88/rsclone pull request #48
Opened 2021-01-19 17:18 UTC by kattitova

2021-01-19 17:36 UTC, DenisOleksiuk approved these changes

2021-01-19 18:49 UTC, Ferri0 requested changes
delete style.css from src/scss folder. Probably its wrong created build

2021-01-20 08:38 UTC, kattitova reviewed
deleted style.css

2021-01-20 10:33 UTC, IgorAleks88 approved these changes

2021-01-20 15:59 UTC, Ferri0 approved these changes

2021-01-20 16:02 UTC, merged